### ISSUE TITLE
piepline failing 

### ISSUE THREAD

**Issue by satishbty** [greninger-lab/revica#2]
Error executing process > 'Consensus_Generation_PE (1)'

Caused by:
  Process `Consensus_Generation_PE (1)` terminated with an error exit status (1)

I am running on Linux system with docker .can you provide pointers to solve this?

**Comment by asereewit** [comment]
I ran your sample using the provided LSD reference and the number of mapped reads is 10, which is essentially nothing. A lot of variants/consensus calling programs have issues with low number of mapped reads.
